Repository gisce/poweremail-modules, pull requests merged in 2024-07, with the labels that each got.

#38 Plantilla genérica de correo electrónico
  poweremail_generic_template/__init__.py
  poweremail_generic_template/__terp__.py
  poweremail_generic_template/data/banners/banner_generic_email_template_body.xml
  poweremail_generic_template/data/banners/banner_generic_email_template_css.xml
  poweremail_generic_template/data/banners/banner_generic_email_template_footer.xml
  poweremail_generic_template/data/banners/banner_generic_email_template_header.xml
  poweremail_generic_template/data/banners/banner_generic_email_template_preheader.xml
  poweremail_generic_template/data/banners/banner_generic_email_template_title.xml
  poweremail_generic_template/emails/generic/components/body/ca.mako
  poweremail_generic_template/emails/generic/components/body/en.mako
  poweremail_generic_template/emails/generic/components/body/es.mako
  poweremail_generic_template/emails/generic/components/footer/en.mako
  poweremail_generic_template/emails/generic/components/header/ca.mako
  poweremail_generic_template/emails/generic/components/header/en.mako
  poweremail_generic_template/emails/generic/components/header/es.mako
  poweremail_generic_template/emails/generic/components/preheader/ca.mako
  poweremail_generic_template/emails/generic/components/preheader/en.mako
  poweremail_generic_template/emails/generic/components/preheader/es.mako
  poweremail_generic_template/emails/generic/components/style.css
  poweremail_generic_template/emails/generic/components/title/ca.mako
  poweremail_generic_template/emails/generic/components/title/en.mako
  poweremail_generic_template/emails/generic/components/title/es.mako
  poweremail_generic_template/emails/generic/index.mako
Labels: deployed, to be merged, deployed PRE

#39 Eliminar código redundante en la plantilla de correo genérica
  poweremail_generic_template/emails/generic/index.mako
Labels: bug

#42 Hacer commit del cursor al actualizarla fecha de última actualización de los emails certificados antes de cerrarlo
  poweremail_signaturit/poweremail_mailbox.py
Labels: bug, to be merged
