Repository gisce/poweremail-modules, pull requests merged in 2024-08, with the labels that each got.

#41 Añadir banner company para la plantilla
  poweremail_generic_template/__terp__.py
  poweremail_generic_template/data/banners/banner_generic_email_template_company.xml
  poweremail_generic_template/emails/generic/components/company/en.mako
  poweremail_generic_template/emails/generic/components/footer/en.mako
  poweremail_generic_template/emails/generic/index.mako
  poweremail_generic_template/migrations/5.0.24.9.0/post-0001_load_generic_template_company_banner.py
Labels: enhancement, to be merged, deployed PRE

#47 Añadir plantilla botón genérico
  poweremail_generic_template/__terp__.py
  poweremail_generic_template/data/banners/banner_generic_email_template_button.xml
  poweremail_generic_template/emails/generic/components/button/en.mako
  poweremail_generic_template/emails/generic/index.mako
  poweremail_generic_template/migrations/5.0.24.9.0/post-0002_load_generic_template_button.py
Labels: to be merged, WIP, deployed PRE

#48 Evaluate preheader banner
  poweremail_generic_template/emails/generic/index.mako
Labels: enhancement

#50 Evitar error cuando no hay events de emails certificados
  poweremail_signaturit/poweremail_mailbox.py
Labels: bug
