Repository gisce/poweremail-modules, pull requests merged in 2025-04, with the labels that each got.

#57 Open related object emails button was in the wizard section instead in the link section
  poweremail_references/poweremail_template.py
Labels: bug, to be merged, ux

#58 Call poweremail callback methods on extra references passed by metadata at the emails generated from the poweremail campaign
  poweremail_campaign/poweremail_campaign_line.py
Labels: enhancement, to be merged

#59 Cuando se marcaba el check de "Enviar solamente un correo" se envíaba más de un correo.
  poweremail_oorq/poweremail_send_wizard.py
  poweremail_oorq/tests/__init__.py
Labels: bug, to be merged, deployed PRE

#56 Implementación de descargar el archivo de auditoria de los correos.
  poweremail_signaturit/__init__.py
  poweremail_signaturit/__terp__.py
  poweremail_signaturit/migrations/5.0.25.5.0/post-0001_download_audit_trail.py
  poweremail_signaturit/poweremail_core.py
  poweremail_signaturit/poweremail_mailbox.py
  poweremail_signaturit/poweremail_mailbox_view.xml
  poweremail_signaturit/report/__init__.py
  poweremail_signaturit/report/data.xml
  poweremail_signaturit/report/signatura_report.py
  poweremail_signaturit/tests/__init__.py
  poweremail_signaturit/tests/fixtures/test_certified_email_audit_trail.pdf
  poweremail_signaturit/tests/test_download_audit_trail.py
Labels: enhancement, to be merged, deployed PRE
